### ISSUE TITLE
Problemer med bruk av plugin

### ISSUE THREAD

**Issue by hognescreentek** [Geta/Geta.EPi.Imageshop#6]
Vi har noen problemer med pluginet til Imageshop (i nyere versjoner av EPIServer). Er det noe dere kunne sett på? Jeg hadde selv problemer med å installere det i EPIServer. Skulle gjerne ha fått oppdatert NUGET-pakken slik at den støttet nyeste versjon av EPIServer. Er dette noe dere har planer om å gjøre?

**Comment by MattisOlsson** [comment]
Hej,

Vi tittar på det så snart vi får tid. Om det brådskar så är det fritt fram att bidra till projektet.

**Comment by tsurnf** [comment]
Hei!
Det ser ut til at det mangler en fil i versjon 2.2.0. InsertImage.aspx refererer til en fil som ikke finnes: <script src="../../tiny_mce_popup.js"></script>

**Comment by hognescreentek** [comment]
Hei,

Kan ta en titt, men det skal ikke ha noen praktisk betydning 😊 Er noe som vært der en stund.

Mvh,
Hogne Hundvebakke
Senior Systemutvikler | Screentek
Sentralbord: (+47) 55 29 61 00
support@screentek.no
Screentek as

**Comment by tsurnf** [comment]
Ok, men når jeg forsøker å sette inn et bilde i teksteditoren, så får jeg feilmelding om at tinyMCEPopup ikke er definert. Tenkte det var pga. den fila som mangler.

**Comment by hognescreentek** [comment]
Usikker. Men insertimage.aspx ligger på client.imageshop.no? Er den alle bruker, så da burde det ikke fungert noen steder. 

Kan uansett se på en fix for dette. Er ikke bra om den referer til filer som ikke eksisterer.

Mvh,
Hogne Hundvebakke
Senior Systemutvikler | Screentek
Sentralbord: (+47) 55 29 61 00
support@screentek.no
Screentek as

**Comment by hognescreentek** [comment]
Hei,

tror jeg har fikset dette. Lager en pull request.

**Comment by hognescreentek** [comment]
Kunne dere oppdatert NUGET når dere oppdaterer basert på pull requestet?

**Comment by hognescreentek** [comment]
Ser at github er oppdatert, så lukker saken.
